### ISSUE TITLE
Duck Card Table

### ISSUE THREAD

**Issue by asm0027** [DuckDisplay/DuckDisplayApp#4]

**Comment by BenjaminCyr** [comment]
6 ducks added to duck facts database at DuckDisplayApp/Duck App/Databases/duckfacts.sqlite3 
American Wigeon, Northern Pintail, Northern Shoveler, Redhead, Wood Duck, Ring-necked Duck

**Comment by BenjaminCyr** [comment]
6 More Ducks added: Lesser Scaup, Cinnamon Teal, and Gadwall, Green-Winged Teal, Mallard, and Canvasback.

**Comment by BenjaminCyr** [comment]
3 More "Ducks" added: Canada Goose, Blue-winged Teal, and American Black Duck. Also added an "ID" column in case we need id numbers. This was all the required ducks, so this issue is being closed. This table is currently in the duck.db file in the Assets folder. Only thing left is to update paths to pictures, sounds, and maps.
